//! Shared Leptos components for Eigenpulse.

mod card;
mod chart_bars;
mod empty_state;
mod error_slot;
mod heatmap;
mod icon;
mod kpi;
mod notifications;
mod page_head;
mod ring;
mod row_action;
mod section_label;
mod sidebar;
mod stat;
mod tabs;
mod tag;
mod toast;
mod topbar;
mod tweaks;

pub use card::Card;
pub use chart_bars::ChartBars;
pub use empty_state::{EmptyState, SkeletonCard, SkeletonKpi};
pub use error_slot::ErrorSlot;
pub use heatmap::Heatmap;
pub use icon::Icon;
pub use kpi::{Direction, Kpi};
pub use notifications::{provide_unread_signal, use_unread_signal};
pub use page_head::PageHead;
pub use ring::Ring;
pub use row_action::{escape_js_single_quoted, RowDeleteAction};
pub use section_label::SectionLabel;
pub use sidebar::Sidebar;
pub use stat::StatRow;
pub use tabs::{TabSpec, Tabs};
pub use tag::{Tag, Tone};
pub use toast::{provide_toast_stack, use_toast, Toast, ToastKind, ToastStack, ToastViewport};
pub use topbar::Topbar;
pub use tweaks::{provide_tweak_state, use_tweaks, Density, Theme, TweakState};
