//! HTTP security headers + Content-Security-Policy for the web app, plus the
//! inlined `theme-init.js`.
//!
//! ## Why the CSP is delivered as a `<meta>` tag, not an HTTP header
//!
//! Leptos's `<HydrationScripts>` / `<AutoReload>` emit **inline** `<script>`s
//! that carry a per-request `nonce`. That nonce is generated by `leptos_axum`
//! *during* rendering (`provide_nonce()` in its `provide_contexts`) and is only
//! retrievable through `leptos::nonce::use_nonce()` from inside the Leptos
//! context. An axum response-header layer runs **outside** that context and
//! cannot learn the value (and `Nonce`'s inner value cannot be constructed by
//! us). A header CSP therefore could never list the matching `'nonce-…'`, so it
//! would block every hydration script — silently degrading each page to a dead,
//! non-interactive SSR snapshot (exactly the hydration footgun AGENTS.md warns
//! about; verified in-browser before this fix).
//!
//! So [`shell()`](crate::app::shell) renders the CSP into a
//! `<meta http-equiv="Content-Security-Policy">` using the **same**
//! `use_nonce()` the scripts use — policy and scripts always carry the identical
//! nonce. The non-CSP headers (nosniff / frame-deny / referrer / opt-in HSTS)
//! stay as HTTP headers ([`security_headers`]). Clickjacking is covered by
//! `X-Frame-Options: DENY`; the CSP `frame-ancestors` directive is ignored when
//! delivered via `<meta>`, so it is intentionally omitted here.
//!
//! This module compiles into BOTH the SSR binary and the hydrate/wasm `[lib]`
//! graph. `shell()` (the only consumer of [`csp_content`]) is itself SSR-only,
//! so the nonce machinery — which would otherwise drag `leptos/nonce` →
//! `getrandom` into the wasm bundle (unsupported on `wasm32-unknown-unknown`
//! without the `js` feature) — is gated behind `#[cfg(feature = "ssr")]`.
//! `theme_init_inline` stays wasm-safe.

/// The exact bytes of `theme-init.js`, embedded at compile time. Inlining this
/// (instead of a render-blocking `<script src>`) removes the cold-cache FOUC:
/// the theme/density attributes are set on `<html>` before first paint without
/// a network round-trip. SSR-only: consumed solely by `shell()`.
#[cfg(feature = "ssr")]
pub const THEME_INIT_JS: &str = include_str!("../../assets/theme-init.js");

/// `<script>…</script>` content for the inlined theme-init IIFE. The trailing
/// newline is trimmed for tidiness. SSR-only: consumed solely by `shell()`.
#[cfg(feature = "ssr")]
pub fn theme_init_inline() -> &'static str {
    THEME_INIT_JS.trim_end_matches('\n')
}

/// Build the page Content-Security-Policy, embedding the Leptos per-request
/// `nonce` so the inlined theme-init script and the `<HydrationScripts>` module
/// bootstrap (which carry this same nonce) are allow-listed. Wasm-safe: pure
/// string construction.
///
/// Directive rationale (one line each):
///
/// - `script-src`: `'self'` + `'wasm-unsafe-eval'` (wasm-bindgen) + the per-request nonce; no `'unsafe-inline'` (every inline script is nonce-gated).
/// - `style-src` keeps `'unsafe-inline'`: Leptos/leptos_meta emit reactive inline styles that cannot be hashed (inline *styles* are far lower risk than scripts).
/// - `connect-src 'self'`: covers the SSE stream and same-origin server-fn POSTs.
/// - `img-src`/`font-src` allow `data:` URIs (inline SVG icons, embedded fonts).
/// - `frame-ancestors` is intentionally absent — `<meta>`-delivered policies ignore it; `X-Frame-Options: DENY` (see [`security_headers`]) is the clickjacking defense.
///
/// SSR-only: `shell()` (the sole caller) is SSR-only, and depending on
/// `leptos::nonce::Nonce` would pull `getrandom` into the wasm bundle.
#[cfg(feature = "ssr")]
pub fn csp_content(nonce: Option<leptos::nonce::Nonce>) -> String {
    let nonce_src = nonce.map(|n| format!(" 'nonce-{n}'")).unwrap_or_default();
    format!(
        "default-src 'self'; \
         base-uri 'self'; \
         object-src 'none'; \
         img-src 'self' data:; \
         font-src 'self' data:; \
         style-src 'self' 'unsafe-inline'; \
         script-src 'self' 'wasm-unsafe-eval'{nonce_src}; \
         connect-src 'self'; \
         manifest-src 'self'; \
         form-action 'self'"
    )
}

#[cfg(feature = "ssr")]
pub use ssr::security_headers;

#[cfg(feature = "ssr")]
mod ssr {
    use axum::{
        extract::Request,
        http::{HeaderName, HeaderValue},
        middleware::Next,
        response::Response,
    };

    const X_CONTENT_TYPE_OPTIONS: HeaderName = HeaderName::from_static("x-content-type-options");
    const X_FRAME_OPTIONS: HeaderName = HeaderName::from_static("x-frame-options");
    const REFERRER_POLICY: HeaderName = HeaderName::from_static("referrer-policy");
    const HSTS: HeaderName = HeaderName::from_static("strict-transport-security");

    /// Whether to emit HSTS. Only meaningful behind TLS; gated on
    /// `EP_COOKIE_SECURE` (the same flag that turns on the `Secure` cookie),
    /// matching AGENTS.md: the LAN/NAS HTTP deployment must not advertise HSTS.
    fn hsts_enabled() -> bool {
        ep_auth::cookie_secure()
    }

    /// axum middleware that stamps the non-CSP security headers onto every
    /// response from the web app router. The CSP itself is delivered via a
    /// `<meta>` tag in `shell()` (see module docs for why). Layer this on the
    /// cookie-session web routes (not the JSON `/api/v1/*` group, whose
    /// responses are not browser-rendered HTML).
    pub async fn security_headers(req: Request, next: Next) -> Response {
        let mut response = next.run(req).await;
        let headers = response.headers_mut();
        headers.insert(X_CONTENT_TYPE_OPTIONS, HeaderValue::from_static("nosniff"));
        headers.insert(X_FRAME_OPTIONS, HeaderValue::from_static("DENY"));
        headers.insert(REFERRER_POLICY, HeaderValue::from_static("same-origin"));
        if hsts_enabled() {
            // 1 year, include subdomains. No `preload` — that is an explicit
            // opt-in submitted to browser preload lists, not a default to assert.
            headers.insert(
                HSTS,
                HeaderValue::from_static("max-age=31536000; includeSubDomains"),
            );
        }
        response
    }
}

#[cfg(all(test, feature = "ssr"))]
mod tests {
    use super::{csp_content, theme_init_inline};

    #[test]
    fn theme_init_inline_has_no_trailing_newline() {
        let inline = theme_init_inline();
        assert!(!inline.ends_with('\n'));
        assert!(inline.starts_with("(function()"));
        assert!(inline.contains("data-theme"));
    }

    #[cfg(feature = "ssr")]
    #[test]
    fn csp_without_nonce_has_core_directives_and_no_nonce_source() {
        let csp = csp_content(None);
        assert!(csp.contains("script-src 'self' 'wasm-unsafe-eval';"));
        assert!(csp.contains("connect-src 'self'"));
        assert!(csp.contains("style-src 'self' 'unsafe-inline'"));
        assert!(csp.contains("object-src 'none'"));
        assert!(!csp.contains("nonce-"));
        // frame-ancestors is intentionally omitted from the meta-delivered CSP.
        assert!(!csp.contains("frame-ancestors"));
    }

    #[cfg(feature = "ssr")]
    #[test]
    fn csp_embeds_the_nonce_when_present() {
        let nonce = leptos::nonce::Nonce::new();
        let token = nonce.to_string();
        let csp = csp_content(Some(nonce));
        assert!(csp.contains(&format!("'wasm-unsafe-eval' 'nonce-{token}'")));
    }
}
